//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 08:21:37 PM BRST 
//


package br.com.maquinapr.dataaccess.complextypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for HistoricoEnvio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoricoEnvio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="contato" type="{http://www.maquina.core.br/domain}Contato"/>
 *         &lt;element name="produto" type="{http://www.maquina.core.br/domain}Produto"/>
 *         &lt;element name="assunto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emailFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emailContato" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="acessos" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="dataEnvio" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="dataAgendamento" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="observacoes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sucesso" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoricoEnvio", propOrder = {
    "id",
    "contato",
    "produto",
    "assunto",
    "emailFrom",
    "emailContato",
    "acessos",
    "dataEnvio",
    "dataAgendamento",
    "observacoes",
    "sucesso"
})
public class HistoricoEnvio {

    protected long id;
    @XmlElement(required = true)
    protected Contato contato;
    @XmlElement(required = true)
    protected Produto produto;
    @XmlElement(required = true)
    protected String assunto;
    @XmlElement(required = true)
    protected String emailFrom;
    @XmlElement(required = true)
    protected String emailContato;
    protected long acessos;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataEnvio;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataAgendamento;
    @XmlElement(required = true)
    protected String observacoes;
    protected long sucesso;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the contato property.
     * 
     * @return
     *     possible object is
     *     {@link Contato }
     *     
     */
    public Contato getContato() {
        return contato;
    }

    /**
     * Sets the value of the contato property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contato }
     *     
     */
    public void setContato(Contato value) {
        this.contato = value;
    }

    /**
     * Gets the value of the produto property.
     * 
     * @return
     *     possible object is
     *     {@link Produto }
     *     
     */
    public Produto getProduto() {
        return produto;
    }

    /**
     * Sets the value of the produto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Produto }
     *     
     */
    public void setProduto(Produto value) {
        this.produto = value;
    }

    /**
     * Gets the value of the assunto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssunto() {
        return assunto;
    }

    /**
     * Sets the value of the assunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssunto(String value) {
        this.assunto = value;
    }

    /**
     * Gets the value of the emailFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailFrom() {
        return emailFrom;
    }

    /**
     * Sets the value of the emailFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailFrom(String value) {
        this.emailFrom = value;
    }

    /**
     * Gets the value of the emailContato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailContato() {
        return emailContato;
    }

    /**
     * Sets the value of the emailContato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailContato(String value) {
        this.emailContato = value;
    }

    /**
     * Gets the value of the acessos property.
     * 
     */
    public long getAcessos() {
        return acessos;
    }

    /**
     * Sets the value of the acessos property.
     * 
     */
    public void setAcessos(long value) {
        this.acessos = value;
    }

    /**
     * Gets the value of the dataEnvio property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataEnvio() {
        return dataEnvio;
    }

    /**
     * Sets the value of the dataEnvio property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataEnvio(XMLGregorianCalendar value) {
        this.dataEnvio = value;
    }

    /**
     * Gets the value of the dataAgendamento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataAgendamento() {
        return dataAgendamento;
    }

    /**
     * Sets the value of the dataAgendamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataAgendamento(XMLGregorianCalendar value) {
        this.dataAgendamento = value;
    }

    /**
     * Gets the value of the observacoes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservacoes() {
        return observacoes;
    }

    /**
     * Sets the value of the observacoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservacoes(String value) {
        this.observacoes = value;
    }

    /**
     * Gets the value of the sucesso property.
     * 
     */
    public long getSucesso() {
        return sucesso;
    }

    /**
     * Sets the value of the sucesso property.
     * 
     */
    public void setSucesso(long value) {
        this.sucesso = value;
    }

}
