//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 08:21:37 PM BRST 
//


package br.com.maquinapr.dataaccess.complextypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LogoTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogoTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="arquivo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="corfundoRGB1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="corfundoRGB2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="topo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ativo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogoTemplate", propOrder = {
    "id",
    "nome",
    "arquivo",
    "path",
    "corfundoRGB1",
    "corfundoRGB2",
    "topo",
    "ativo"
})
public class LogoTemplate {

    protected long id;
    @XmlElement(required = true)
    protected String nome;
    @XmlElement(required = true)
    protected String arquivo;
    @XmlElement(required = true)
    protected String path;
    @XmlElement(required = true)
    protected String corfundoRGB1;
    @XmlElement(required = true)
    protected String corfundoRGB2;
    @XmlElement(required = true)
    protected String topo;
    protected long ativo;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the arquivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArquivo() {
        return arquivo;
    }

    /**
     * Sets the value of the arquivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArquivo(String value) {
        this.arquivo = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the corfundoRGB1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorfundoRGB1() {
        return corfundoRGB1;
    }

    /**
     * Sets the value of the corfundoRGB1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorfundoRGB1(String value) {
        this.corfundoRGB1 = value;
    }

    /**
     * Gets the value of the corfundoRGB2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorfundoRGB2() {
        return corfundoRGB2;
    }

    /**
     * Sets the value of the corfundoRGB2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorfundoRGB2(String value) {
        this.corfundoRGB2 = value;
    }

    /**
     * Gets the value of the topo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopo() {
        return topo;
    }

    /**
     * Sets the value of the topo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopo(String value) {
        this.topo = value;
    }

    /**
     * Gets the value of the ativo property.
     * 
     */
    public long getAtivo() {
        return ativo;
    }

    /**
     * Sets the value of the ativo property.
     * 
     */
    public void setAtivo(long value) {
        this.ativo = value;
    }

}
