//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 08:21:37 PM BRST 
//


package br.com.maquinapr.dataaccess.complextypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NoticiaClipping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NoticiaClipping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="webURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mobileURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noticia" type="{http://www.maquina.core.br/domain}Noticia"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NoticiaClipping", propOrder = {
    "id",
    "webURL",
    "mobileURL",
    "noticia"
})
public class NoticiaClipping {

    protected long id;
    @XmlElement(required = true)
    protected String webURL;
    @XmlElement(required = true)
    protected String mobileURL;
    @XmlElement(required = true)
    protected Noticia noticia;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the webURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebURL() {
        return webURL;
    }

    /**
     * Sets the value of the webURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebURL(String value) {
        this.webURL = value;
    }

    /**
     * Gets the value of the mobileURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileURL() {
        return mobileURL;
    }

    /**
     * Sets the value of the mobileURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileURL(String value) {
        this.mobileURL = value;
    }

    /**
     * Gets the value of the noticia property.
     * 
     * @return
     *     possible object is
     *     {@link Noticia }
     *     
     */
    public Noticia getNoticia() {
        return noticia;
    }

    /**
     * Sets the value of the noticia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Noticia }
     *     
     */
    public void setNoticia(Noticia value) {
        this.noticia = value;
    }

}
