//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 08:21:37 PM BRST 
//


package br.com.maquinapr.dataaccess.complextypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Noticia complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Noticia">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="titulo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="conteudo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ordem" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="destaque" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="editada" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="produto" type="{http://www.maquina.core.br/domain}Produto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Noticia", propOrder = {
    "id",
    "titulo",
    "conteudo",
    "ordem",
    "destaque",
    "editada",
    "produto"
})
public class Noticia {

    protected long id;
    @XmlElement(required = true)
    protected String titulo;
    @XmlElement(required = true)
    protected String conteudo;
    protected long ordem;
    protected long destaque;
    protected long editada;
    @XmlElement(required = true)
    protected Produto produto;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the titulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * Sets the value of the titulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitulo(String value) {
        this.titulo = value;
    }

    /**
     * Gets the value of the conteudo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConteudo() {
        return conteudo;
    }

    /**
     * Sets the value of the conteudo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConteudo(String value) {
        this.conteudo = value;
    }

    /**
     * Gets the value of the ordem property.
     * 
     */
    public long getOrdem() {
        return ordem;
    }

    /**
     * Sets the value of the ordem property.
     * 
     */
    public void setOrdem(long value) {
        this.ordem = value;
    }

    /**
     * Gets the value of the destaque property.
     * 
     */
    public long getDestaque() {
        return destaque;
    }

    /**
     * Sets the value of the destaque property.
     * 
     */
    public void setDestaque(long value) {
        this.destaque = value;
    }

    /**
     * Gets the value of the editada property.
     * 
     */
    public long getEditada() {
        return editada;
    }

    /**
     * Sets the value of the editada property.
     * 
     */
    public void setEditada(long value) {
        this.editada = value;
    }

    /**
     * Gets the value of the produto property.
     * 
     * @return
     *     possible object is
     *     {@link Produto }
     *     
     */
    public Produto getProduto() {
        return produto;
    }

    /**
     * Sets the value of the produto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Produto }
     *     
     */
    public void setProduto(Produto value) {
        this.produto = value;
    }

}
