//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 08:21:37 PM BRST 
//


package br.com.maquinapr.dataaccess.complextypes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.maquinapr.dataaccess.complextypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListaAgendamentoDisparos_QNAME = new QName("http://www.maquina.core.br/domain", "listaAgendamentoDisparos");
    private final static QName _ListaLogoTemplates_QNAME = new QName("http://www.maquina.core.br/domain", "listaLogoTemplates");
    private final static QName _ListaLogoMaquinas_QNAME = new QName("http://www.maquina.core.br/domain", "listaLogoMaquinas");
    private final static QName _ListaDisparos_QNAME = new QName("http://www.maquina.core.br/domain", "listaDisparos");
    private final static QName _ModeloTitulo_QNAME = new QName("http://www.maquina.core.br/domain", "modeloTitulo");
    private final static QName _LogoTemplate_QNAME = new QName("http://www.maquina.core.br/domain", "logoTemplate");
    private final static QName _Disparo_QNAME = new QName("http://www.maquina.core.br/domain", "disparo");
    private final static QName _Produto_QNAME = new QName("http://www.maquina.core.br/domain", "produto");
    private final static QName _Noticia_QNAME = new QName("http://www.maquina.core.br/domain", "noticia");
    private final static QName _ListaLogoClientes_QNAME = new QName("http://www.maquina.core.br/domain", "listaLogoClientes");
    private final static QName _ListaSenders_QNAME = new QName("http://www.maquina.core.br/domain", "listaSenders");
    private final static QName _ListaNoticias_QNAME = new QName("http://www.maquina.core.br/domain", "listaNoticias");
    private final static QName _ListaModeloTitulos_QNAME = new QName("http://www.maquina.core.br/domain", "listaModeloTitulos");
    private final static QName _LogoAssinatura_QNAME = new QName("http://www.maquina.core.br/domain", "logoAssinatura");
    private final static QName _Sender_QNAME = new QName("http://www.maquina.core.br/domain", "sender");
    private final static QName _ListaLogDisparos_QNAME = new QName("http://www.maquina.core.br/domain", "listaLogDisparos");
    private final static QName _ListaContatoGrupos_QNAME = new QName("http://www.maquina.core.br/domain", "listaContatoGrupos");
    private final static QName _ContatoGrupo_QNAME = new QName("http://www.maquina.core.br/domain", "contatoGrupo");
    private final static QName _ListaLogoProdutos_QNAME = new QName("http://www.maquina.core.br/domain", "listaLogoProdutos");
    private final static QName _LogoCliente_QNAME = new QName("http://www.maquina.core.br/domain", "logoCliente");
    private final static QName _ListaProdutos_QNAME = new QName("http://www.maquina.core.br/domain", "listaProdutos");
    private final static QName _ListaHistoricoEnvios_QNAME = new QName("http://www.maquina.core.br/domain", "listaHistoricoEnvios");
    private final static QName _LogoProduto_QNAME = new QName("http://www.maquina.core.br/domain", "logoProduto");
    private final static QName _ListaLogoAssinaturas_QNAME = new QName("http://www.maquina.core.br/domain", "listaLogoAssinaturas");
    private final static QName _ListaModelos_QNAME = new QName("http://www.maquina.core.br/domain", "listaModelos");
    private final static QName _Contato_QNAME = new QName("http://www.maquina.core.br/domain", "contato");
    private final static QName _LogoMaquina_QNAME = new QName("http://www.maquina.core.br/domain", "logoMaquina");
    private final static QName _AgendamentoDisparo_QNAME = new QName("http://www.maquina.core.br/domain", "agendamentoDisparo");
    private final static QName _NoticiaClipping_QNAME = new QName("http://www.maquina.core.br/domain", "noticiaClipping");
    private final static QName _Modelo_QNAME = new QName("http://www.maquina.core.br/domain", "modelo");
    private final static QName _HistoricoEnvio_QNAME = new QName("http://www.maquina.core.br/domain", "historicoEnvio");
    private final static QName _ListaContatos_QNAME = new QName("http://www.maquina.core.br/domain", "listaContatos");
    private final static QName _ListaNoticiaClippings_QNAME = new QName("http://www.maquina.core.br/domain", "listaNoticiaClippings");
    private final static QName _LogDisparo_QNAME = new QName("http://www.maquina.core.br/domain", "logDisparo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.maquinapr.dataaccess.complextypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListaProduto }
     * 
     */
    public ListaProduto createListaProduto() {
        return new ListaProduto();
    }

    /**
     * Create an instance of {@link NoticiaClipping }
     * 
     */
    public NoticiaClipping createNoticiaClipping() {
        return new NoticiaClipping();
    }

    /**
     * Create an instance of {@link ListaLogoCliente }
     * 
     */
    public ListaLogoCliente createListaLogoCliente() {
        return new ListaLogoCliente();
    }

    /**
     * Create an instance of {@link ListaLogDisparo }
     * 
     */
    public ListaLogDisparo createListaLogDisparo() {
        return new ListaLogDisparo();
    }

    /**
     * Create an instance of {@link ContatoGrupo }
     * 
     */
    public ContatoGrupo createContatoGrupo() {
        return new ContatoGrupo();
    }

    /**
     * Create an instance of {@link ListaSender }
     * 
     */
    public ListaSender createListaSender() {
        return new ListaSender();
    }

    /**
     * Create an instance of {@link LogoProduto }
     * 
     */
    public LogoProduto createLogoProduto() {
        return new LogoProduto();
    }

    /**
     * Create an instance of {@link Modelo }
     * 
     */
    public Modelo createModelo() {
        return new Modelo();
    }

    /**
     * Create an instance of {@link ListaHistoricoEnvio }
     * 
     */
    public ListaHistoricoEnvio createListaHistoricoEnvio() {
        return new ListaHistoricoEnvio();
    }

    /**
     * Create an instance of {@link LogoAssinatura }
     * 
     */
    public LogoAssinatura createLogoAssinatura() {
        return new LogoAssinatura();
    }

    /**
     * Create an instance of {@link Noticia }
     * 
     */
    public Noticia createNoticia() {
        return new Noticia();
    }

    /**
     * Create an instance of {@link LogoMaquina }
     * 
     */
    public LogoMaquina createLogoMaquina() {
        return new LogoMaquina();
    }

    /**
     * Create an instance of {@link HistoricoEnvio }
     * 
     */
    public HistoricoEnvio createHistoricoEnvio() {
        return new HistoricoEnvio();
    }

    /**
     * Create an instance of {@link ListaLogoProduto }
     * 
     */
    public ListaLogoProduto createListaLogoProduto() {
        return new ListaLogoProduto();
    }

    /**
     * Create an instance of {@link ListaAgendamentoDisparo }
     * 
     */
    public ListaAgendamentoDisparo createListaAgendamentoDisparo() {
        return new ListaAgendamentoDisparo();
    }

    /**
     * Create an instance of {@link ListaModelo }
     * 
     */
    public ListaModelo createListaModelo() {
        return new ListaModelo();
    }

    /**
     * Create an instance of {@link ListaNoticiaClipping }
     * 
     */
    public ListaNoticiaClipping createListaNoticiaClipping() {
        return new ListaNoticiaClipping();
    }

    /**
     * Create an instance of {@link ListaLogoMaquina }
     * 
     */
    public ListaLogoMaquina createListaLogoMaquina() {
        return new ListaLogoMaquina();
    }

    /**
     * Create an instance of {@link Sender }
     * 
     */
    public Sender createSender() {
        return new Sender();
    }

    /**
     * Create an instance of {@link ListaModeloTitulo }
     * 
     */
    public ListaModeloTitulo createListaModeloTitulo() {
        return new ListaModeloTitulo();
    }

    /**
     * Create an instance of {@link LogoCliente }
     * 
     */
    public LogoCliente createLogoCliente() {
        return new LogoCliente();
    }

    /**
     * Create an instance of {@link Contato }
     * 
     */
    public Contato createContato() {
        return new Contato();
    }

    /**
     * Create an instance of {@link Produto }
     * 
     */
    public Produto createProduto() {
        return new Produto();
    }

    /**
     * Create an instance of {@link ListaContatoGrupo }
     * 
     */
    public ListaContatoGrupo createListaContatoGrupo() {
        return new ListaContatoGrupo();
    }

    /**
     * Create an instance of {@link ListaLogoTemplate }
     * 
     */
    public ListaLogoTemplate createListaLogoTemplate() {
        return new ListaLogoTemplate();
    }

    /**
     * Create an instance of {@link ModeloTitulo }
     * 
     */
    public ModeloTitulo createModeloTitulo() {
        return new ModeloTitulo();
    }

    /**
     * Create an instance of {@link LogoTemplate }
     * 
     */
    public LogoTemplate createLogoTemplate() {
        return new LogoTemplate();
    }

    /**
     * Create an instance of {@link ListaNoticia }
     * 
     */
    public ListaNoticia createListaNoticia() {
        return new ListaNoticia();
    }

    /**
     * Create an instance of {@link LogDisparo }
     * 
     */
    public LogDisparo createLogDisparo() {
        return new LogDisparo();
    }

    /**
     * Create an instance of {@link ListaDisparo }
     * 
     */
    public ListaDisparo createListaDisparo() {
        return new ListaDisparo();
    }

    /**
     * Create an instance of {@link ListaContato }
     * 
     */
    public ListaContato createListaContato() {
        return new ListaContato();
    }

    /**
     * Create an instance of {@link Disparo }
     * 
     */
    public Disparo createDisparo() {
        return new Disparo();
    }

    /**
     * Create an instance of {@link ListaLogoAssinatura }
     * 
     */
    public ListaLogoAssinatura createListaLogoAssinatura() {
        return new ListaLogoAssinatura();
    }

    /**
     * Create an instance of {@link AgendamentoDisparo }
     * 
     */
    public AgendamentoDisparo createAgendamentoDisparo() {
        return new AgendamentoDisparo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaAgendamentoDisparo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaAgendamentoDisparos")
    public JAXBElement<ListaAgendamentoDisparo> createListaAgendamentoDisparos(ListaAgendamentoDisparo value) {
        return new JAXBElement<ListaAgendamentoDisparo>(_ListaAgendamentoDisparos_QNAME, ListaAgendamentoDisparo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaLogoTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaLogoTemplates")
    public JAXBElement<ListaLogoTemplate> createListaLogoTemplates(ListaLogoTemplate value) {
        return new JAXBElement<ListaLogoTemplate>(_ListaLogoTemplates_QNAME, ListaLogoTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaLogoMaquina }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaLogoMaquinas")
    public JAXBElement<ListaLogoMaquina> createListaLogoMaquinas(ListaLogoMaquina value) {
        return new JAXBElement<ListaLogoMaquina>(_ListaLogoMaquinas_QNAME, ListaLogoMaquina.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaDisparo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaDisparos")
    public JAXBElement<ListaDisparo> createListaDisparos(ListaDisparo value) {
        return new JAXBElement<ListaDisparo>(_ListaDisparos_QNAME, ListaDisparo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModeloTitulo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "modeloTitulo")
    public JAXBElement<ModeloTitulo> createModeloTitulo(ModeloTitulo value) {
        return new JAXBElement<ModeloTitulo>(_ModeloTitulo_QNAME, ModeloTitulo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "logoTemplate")
    public JAXBElement<LogoTemplate> createLogoTemplate(LogoTemplate value) {
        return new JAXBElement<LogoTemplate>(_LogoTemplate_QNAME, LogoTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Disparo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "disparo")
    public JAXBElement<Disparo> createDisparo(Disparo value) {
        return new JAXBElement<Disparo>(_Disparo_QNAME, Disparo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Produto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "produto")
    public JAXBElement<Produto> createProduto(Produto value) {
        return new JAXBElement<Produto>(_Produto_QNAME, Produto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Noticia }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "noticia")
    public JAXBElement<Noticia> createNoticia(Noticia value) {
        return new JAXBElement<Noticia>(_Noticia_QNAME, Noticia.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaLogoCliente }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaLogoClientes")
    public JAXBElement<ListaLogoCliente> createListaLogoClientes(ListaLogoCliente value) {
        return new JAXBElement<ListaLogoCliente>(_ListaLogoClientes_QNAME, ListaLogoCliente.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaSender }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaSenders")
    public JAXBElement<ListaSender> createListaSenders(ListaSender value) {
        return new JAXBElement<ListaSender>(_ListaSenders_QNAME, ListaSender.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaNoticia }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaNoticias")
    public JAXBElement<ListaNoticia> createListaNoticias(ListaNoticia value) {
        return new JAXBElement<ListaNoticia>(_ListaNoticias_QNAME, ListaNoticia.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaModeloTitulo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaModeloTitulos")
    public JAXBElement<ListaModeloTitulo> createListaModeloTitulos(ListaModeloTitulo value) {
        return new JAXBElement<ListaModeloTitulo>(_ListaModeloTitulos_QNAME, ListaModeloTitulo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoAssinatura }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "logoAssinatura")
    public JAXBElement<LogoAssinatura> createLogoAssinatura(LogoAssinatura value) {
        return new JAXBElement<LogoAssinatura>(_LogoAssinatura_QNAME, LogoAssinatura.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sender }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "sender")
    public JAXBElement<Sender> createSender(Sender value) {
        return new JAXBElement<Sender>(_Sender_QNAME, Sender.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaLogDisparo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaLogDisparos")
    public JAXBElement<ListaLogDisparo> createListaLogDisparos(ListaLogDisparo value) {
        return new JAXBElement<ListaLogDisparo>(_ListaLogDisparos_QNAME, ListaLogDisparo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaContatoGrupo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaContatoGrupos")
    public JAXBElement<ListaContatoGrupo> createListaContatoGrupos(ListaContatoGrupo value) {
        return new JAXBElement<ListaContatoGrupo>(_ListaContatoGrupos_QNAME, ListaContatoGrupo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContatoGrupo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "contatoGrupo")
    public JAXBElement<ContatoGrupo> createContatoGrupo(ContatoGrupo value) {
        return new JAXBElement<ContatoGrupo>(_ContatoGrupo_QNAME, ContatoGrupo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaLogoProduto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaLogoProdutos")
    public JAXBElement<ListaLogoProduto> createListaLogoProdutos(ListaLogoProduto value) {
        return new JAXBElement<ListaLogoProduto>(_ListaLogoProdutos_QNAME, ListaLogoProduto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoCliente }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "logoCliente")
    public JAXBElement<LogoCliente> createLogoCliente(LogoCliente value) {
        return new JAXBElement<LogoCliente>(_LogoCliente_QNAME, LogoCliente.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaProduto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaProdutos")
    public JAXBElement<ListaProduto> createListaProdutos(ListaProduto value) {
        return new JAXBElement<ListaProduto>(_ListaProdutos_QNAME, ListaProduto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaHistoricoEnvio }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaHistoricoEnvios")
    public JAXBElement<ListaHistoricoEnvio> createListaHistoricoEnvios(ListaHistoricoEnvio value) {
        return new JAXBElement<ListaHistoricoEnvio>(_ListaHistoricoEnvios_QNAME, ListaHistoricoEnvio.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoProduto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "logoProduto")
    public JAXBElement<LogoProduto> createLogoProduto(LogoProduto value) {
        return new JAXBElement<LogoProduto>(_LogoProduto_QNAME, LogoProduto.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaLogoAssinatura }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaLogoAssinaturas")
    public JAXBElement<ListaLogoAssinatura> createListaLogoAssinaturas(ListaLogoAssinatura value) {
        return new JAXBElement<ListaLogoAssinatura>(_ListaLogoAssinaturas_QNAME, ListaLogoAssinatura.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaModelo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaModelos")
    public JAXBElement<ListaModelo> createListaModelos(ListaModelo value) {
        return new JAXBElement<ListaModelo>(_ListaModelos_QNAME, ListaModelo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Contato }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "contato")
    public JAXBElement<Contato> createContato(Contato value) {
        return new JAXBElement<Contato>(_Contato_QNAME, Contato.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoMaquina }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "logoMaquina")
    public JAXBElement<LogoMaquina> createLogoMaquina(LogoMaquina value) {
        return new JAXBElement<LogoMaquina>(_LogoMaquina_QNAME, LogoMaquina.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgendamentoDisparo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "agendamentoDisparo")
    public JAXBElement<AgendamentoDisparo> createAgendamentoDisparo(AgendamentoDisparo value) {
        return new JAXBElement<AgendamentoDisparo>(_AgendamentoDisparo_QNAME, AgendamentoDisparo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoticiaClipping }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "noticiaClipping")
    public JAXBElement<NoticiaClipping> createNoticiaClipping(NoticiaClipping value) {
        return new JAXBElement<NoticiaClipping>(_NoticiaClipping_QNAME, NoticiaClipping.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Modelo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "modelo")
    public JAXBElement<Modelo> createModelo(Modelo value) {
        return new JAXBElement<Modelo>(_Modelo_QNAME, Modelo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistoricoEnvio }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "historicoEnvio")
    public JAXBElement<HistoricoEnvio> createHistoricoEnvio(HistoricoEnvio value) {
        return new JAXBElement<HistoricoEnvio>(_HistoricoEnvio_QNAME, HistoricoEnvio.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaContato }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaContatos")
    public JAXBElement<ListaContato> createListaContatos(ListaContato value) {
        return new JAXBElement<ListaContato>(_ListaContatos_QNAME, ListaContato.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaNoticiaClipping }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "listaNoticiaClippings")
    public JAXBElement<ListaNoticiaClipping> createListaNoticiaClippings(ListaNoticiaClipping value) {
        return new JAXBElement<ListaNoticiaClipping>(_ListaNoticiaClippings_QNAME, ListaNoticiaClipping.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogDisparo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.maquina.core.br/domain", name = "logDisparo")
    public JAXBElement<LogDisparo> createLogDisparo(LogDisparo value) {
        return new JAXBElement<LogDisparo>(_LogDisparo_QNAME, LogDisparo.class, null, value);
    }

}
