//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 08:21:37 PM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.maquina.core.br/domain", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.maquinapr.dataaccess.complextypes;
