//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 08:21:37 PM BRST 
//


package br.com.maquinapr.dataaccess.complextypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Produto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Produto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="templateExterno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="observacoes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tituloEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ativo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="aplicarlogo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="modelo" type="{http://www.maquina.core.br/domain}Modelo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Produto", propOrder = {
    "id",
    "data",
    "templateExterno",
    "observacoes",
    "tituloEmail",
    "tipo",
    "ativo",
    "aplicarlogo",
    "modelo"
})
public class Produto {

    protected long id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar data;
    @XmlElement(required = true)
    protected String templateExterno;
    @XmlElement(required = true)
    protected String observacoes;
    @XmlElement(required = true)
    protected String tituloEmail;
    protected long tipo;
    protected long ativo;
    protected long aplicarlogo;
    @XmlElement(required = true)
    protected Modelo modelo;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setData(XMLGregorianCalendar value) {
        this.data = value;
    }

    /**
     * Gets the value of the templateExterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateExterno() {
        return templateExterno;
    }

    /**
     * Sets the value of the templateExterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateExterno(String value) {
        this.templateExterno = value;
    }

    /**
     * Gets the value of the observacoes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservacoes() {
        return observacoes;
    }

    /**
     * Sets the value of the observacoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservacoes(String value) {
        this.observacoes = value;
    }

    /**
     * Gets the value of the tituloEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTituloEmail() {
        return tituloEmail;
    }

    /**
     * Sets the value of the tituloEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTituloEmail(String value) {
        this.tituloEmail = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     */
    public long getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     */
    public void setTipo(long value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the ativo property.
     * 
     */
    public long getAtivo() {
        return ativo;
    }

    /**
     * Sets the value of the ativo property.
     * 
     */
    public void setAtivo(long value) {
        this.ativo = value;
    }

    /**
     * Gets the value of the aplicarlogo property.
     * 
     */
    public long getAplicarlogo() {
        return aplicarlogo;
    }

    /**
     * Sets the value of the aplicarlogo property.
     * 
     */
    public void setAplicarlogo(long value) {
        this.aplicarlogo = value;
    }

    /**
     * Gets the value of the modelo property.
     * 
     * @return
     *     possible object is
     *     {@link Modelo }
     *     
     */
    public Modelo getModelo() {
        return modelo;
    }

    /**
     * Sets the value of the modelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modelo }
     *     
     */
    public void setModelo(Modelo value) {
        this.modelo = value;
    }

}
